name: Deploy to Hetzner

on:
  push:
    branches: [ dev-deploy-test ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t blink-fe .

      - name: Exportar Docker image
        run: docker save blink-fe | gzip > blink-fe.tar.gz

      - name: Enviar imagem para Hetzner
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "blink-fe.tar.gz"
          target: "/opt/frontend/dev/"

      - name: Executar container no Hetzner
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker load < /opt/frontend/dev/blink-fe.tar.gz
            docker stop blink-fe-dev || true
            docker rm blink-fe-dev || true
            docker run -d --name blink-fe-dev -p 3002:3000 --network blink-docker-network
